Vagrant.configure("2") do |config|

      #MACCHINA 1

    config.vm.define "PRX-01" do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "PRX-01"
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.synced_folder "./condivisa", "/condivisa"
    config.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y apache2
    SHELL

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end

      #MACCHINA 2

   config.vm.define "WEB-01" do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "WEB-01"
    config.vm.network "private_network", ip: "192.168.56.12"
    config.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y apache2
    SHELL
    
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end

   #MACCHINA 3

   config.vm.define "WEB-02" do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "WEB-02"
    config.vm.network "private_network", ip: "192.168.56.13"
    config.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y apache2
    SHELL
    
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end
end