Vagrant.configure("2") do |config|

  # MACCHINA 1
  config.vm.define "ub1" do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "ub1"
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.synced_folder "./condivisa", "/condivisa"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # MACCHINA 2
  config.vm.define "ub2" do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "ub2"
    config.vm.network "private_network", ip: "192.168.56.12"
    config.vm.synced_folder "./condivisa", "/condivisa"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.limit = "all"
    end
  end

end