Vagrant.configure("2") do |config|

       #MACCHINA 1

    config.vm.define "rocky1" do |config|
    config.vm.box = "generic/rocky9"
    config.vm.hostname = "rocky1"
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.synced_folder "./condivisa", "/condivisa"
    config.vm.provision "shell", inline: <<-SHELL
        dnf update
        dnf install -y podman
        ssh-keygen -t ed25519 -N ""
        cp /root/.ssh/id_ed25519.pub /condivisa/rocky1.pub
        SHELL
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end

      #MACCHINA 2

   config.vm.define "rocky2" do |config|
    config.vm.box = "generic/rocky9"
    config.vm.hostname = "rocky2"
    config.vm.network "private_network", ip: "192.168.56.12"
    config.vm.synced_folder "./condivisa", "/condivisa"
    config.vm.provision "shell", inline: <<-SHELL
        dnf update
        dnf install -y podman
        cat /condivisa/rocky1.pub >> /root/.ssh/authorized_keys
        SHELL
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end
end