Vagrant.configure("2") do |config|
    config.vm.define "rocky1" do |config|
    config.vm.box = "generic/rocky8"
    config.vm.hostname = "rocky1"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.synced_folder "./condivisa", "/condivisa"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end

   config.vm.define "rocky3" do |config|
    config.vm.box = "generic/rocky8"
    config.vm.hostname = "rocky3"
    config.vm.network "private_network", ip: "192.168.56.12"
    config.vm.synced_folder "./condivisa", "/condivisa"

    config.vm.provision "shell", inline: <<-SHELL
    dnf install podman -y   
    sudo -u vagrant podman create --name pong alpine sleep 60
    cat /condivisa/id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
  end
end
