Vagrant.configure("2") do |config|

config.vm.define "ub" do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "ub"
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.provision "ansible" do |ansible|
      
      # da inserire il nome del playbook da eseguire
      ansible.playbook = "playbook"

      # utilizzata solo per playbook-esercizi-1-2.yaml
      ansible.ask_vault_pass = true

    end

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end